#!/usr/bin/env python3
"""Write readme.txt, a plain-ASCII (LF) copy of README.md for the JAE Data Archive deposit.
Run from the package root after editing README.md:  python tools/make_readme_txt.py"""
import os
import unicodedata

PKG = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
REPL = {"ü": "ue", "ö": "oe", "ä": "ae", "Ü": "Ue", "Ö": "Oe", "Ä": "Ae", "ß": "ss", "é": "e", "è": "e",
        "ê": "e", "à": "a", "á": "a", "ó": "o", "ø": "o", "æ": "ae", "å": "aa", "ñ": "n", "–": "-", "—": "-",
        "“": '"', "”": '"', "‘": "'", "’": "'", "…": "...", "×": "x", "≤": "<=", "≥": ">="}


def to_ascii(text):
    out = []
    for ch in text:
        if ord(ch) < 128:
            out.append(ch)
        elif ch in REPL:
            out.append(REPL[ch])
        else:
            base = unicodedata.normalize("NFKD", ch).encode("ascii", "ignore").decode("ascii")
            out.append(base if base else "?")
    return "".join(out)


def main():
    md = open(os.path.join(PKG, "README.md"), encoding="utf-8").read()
    header = ("This is the plain-text (ASCII) copy of README.md, generated by tools/make_readme_txt.py.\n"
              "Markdown markup is kept for structure; the content is identical.\n\n")
    txt = to_ascii(header + md).replace("\r\n", "\n")
    assert all(ord(c) < 128 for c in txt)
    with open(os.path.join(PKG, "readme.txt"), "w", encoding="ascii", newline="\n") as fh:
        fh.write(txt)
    print("readme.txt written (%d bytes, ASCII)" % len(txt))


if __name__ == "__main__":
    main()
